include ./nord.conf
background_opacity 0.8

font_family Fira Code Nerd Font Complete Mono
bold_font Fira Code Bold Nerd Font Complete Mono
italic_font Fira Code Italic Nerd Font Complete Mono
bold_italic_font Fira Code Italic Nerd Font Complete Mono
font_size 12
adjust_line_height 125%

cursor_blink_interval 0
window_padding_width 10
hide_window_decorations yes
enable_audio_bell no
